# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('temperature_error', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('dew_point_error', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('relative_humidity_error', models.FloatField()),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('pressure_error', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='humiditymeasurement',
            unique_together=set([('location', 'time')]),
        ),
    ]
