# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20180722_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humiditymeasurement',
            options={'ordering': ('-time', 'location'), 'verbose_name': 'Humidity Measurement'},
        ),
    ]
