# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0008_auto_20180612_1220'),
        ('courts', '0003_auto_20180722_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondensationLocation',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Condensation Location',
            },
        ),
        migrations.CreateModel(
            name='CondensationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.ManyToManyField(to='courts.CondensationLocation')),
                ('comment', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usermodel.Player')),
            ],
            options={
                'verbose_name': 'Condensation Report',
            },
        ),
        migrations.RenameModel(
            old_name='HumidityMeasurement',
            new_name='ClimateMeasurement',
        ),
        migrations.AlterModelOptions(
            name='climatemeasurement',
            options={'ordering': ('-time', 'location'), 'verbose_name': 'Climate Measurement'},
        ),
    ]
