# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import wsrc.utils.timezones


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20180724_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condensationlocation',
            options={'ordering': ('name',), 'verbose_name': 'Condensation Location'},
        ),
        migrations.AlterModelOptions(
            name='condensationreport',
            options={'ordering': ('-time',), 'verbose_name': 'Condensation Report'},
        ),
        migrations.AlterField(
            model_name='condensationreport',
            name='time',
            field=models.DateTimeField(default=wsrc.utils.timezones.nearest_last_quarter_hour, verbose_name=b'Observed Time'),
        ),
    ]
