# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0005_auto_20180801_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystemevent',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            "UPDATE courts_bookingsystemevent SET created_by_user_id = (SELECT user_id FROM usermodel_player WHERE id = created_by_id)",
            migrations.RunSQL.noop
        ),
    ]
