# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0006_bookingsystemevent_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystemevent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookingsystemevent',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingsystemevent',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingsystemevent',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunSQL(
            "UPDATE courts_bookingsystemevent SET last_updated = created_time WHERE created_time IS NOT null",
            migrations.RunSQL.noop
        ),
    ]
