# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0007_auto_20180918_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystemevent',
            name='no_show_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='none+', to=settings.AUTH_USER_MODEL),
        ),
    ]
