# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_bookingsystemevent_no_show_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystemevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
