# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'courts', '0010_auto_20180926_1817'), (b'courts', '0011_auto_20180926_2343'), (b'courts', '0012_bookingsystemeventauditentry_update_type')]

    dependencies = [
        ('courts', '0009_bookingsystemevent_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSystemEventAuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(choices=[(b'I', b'Member'), (b'E', b'Club')], max_length=1)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'ordering': ('-booking__pk', '-updated'),
                'verbose_name': 'Booking Audit Entry',
                'verbose_name_plural': 'Booking Audit Entries',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingsystemevent',
            options={'ordering': ('-start_time', '-court'), 'verbose_name': 'Booking'},
        ),
        migrations.AddField(
            model_name='bookingsystemeventauditentry',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.BookingSystemEvent'),
        ),
        migrations.AddField(
            model_name='bookingsystemeventauditentry',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingsystemeventauditentry',
            name='update_type',
            field=models.CharField(choices=[(b'C', b'Create'), (b'U', b'Update'), (b'D', b'Delete')], default='U', max_length=1),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """INSERT INTO courts_bookingsystemeventauditentry (name, description, event_type, updated, booking_id, updated_by_id, update_type) SELECT E.name, E.description, E.event_type, E.last_updated as updated, E.id as booking_id, U.id, "C" as update_type FROM courts_bookingsystemevent E RIGHT JOIN auth_user U ON E.created_by_id = U.id WHERE E.event_id IS NOT NULL;""",
            migrations.RunSQL.noop
        ),
    ]
