# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-30 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_bookingsystemeventauditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfilter',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodel.Player'),
        ),
    ]
