# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_newsitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-display_date'], 'verbose_name': 'News Item'},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
