#!/usr/bin/env python

import getopt
import logging
import os
import sys

from wsrc.utils import sync_utils

import wsrc.site.settings.settings as settings  

def make_username(csv_record):
  return "_".join([csv_record["firstname"].lower(), csv_record["surname"].lower()])

def persist_member_details(csv_record):
  from wsrc.site.usermodel.models import User
  user = User(first_name=csv_record["firstname"],
              last_name=csv_record["surname"],
              email=csv_record["email"],
              is_active=csv_record["active"],
              username=make_username(csv_record)
              )
  user.save()
  user.set_password(settings._WSRC_SETTINGS["default_pw"])
  user.save()
  user.player.cell_phone=csv_record["mobile_phone"]
  user.player.other_phone=csv_record["home_phone"]
  user.player.save()

def add_former_member(csv_filename, first, last):

  csv_records = sync_utils.parse_csv(csv_filename)
  csv_records = sync_utils.BooleanFieldWrapper.wrap_records(csv_records, "active")

  records = [r for r in csv_records if r["firstname"] == first and r["surname"] == last]
  if len(records) == 0:
    raise Exception("Could not find record of %(first)s %(last)s" % locals())
  if len(records) > 1:
    nrecords = len(records)
    raise Exception("Expected one record of %(first)s %(last)s, got %(nrecords)d" % locals())

  persist_member_details(records[0])
  
def sync_membership_records(csv_filename):

  from wsrc.site.usermodel.models import Player, User

  # TODO - invalididate members in DB when set invalid in CSV file

  def is_valid_member_predicate(record):
    return (len(record["surname"].strip()) > 0) and \
        not "2099" in record["joiningdate"] and \
        record["active"].lower()[0] == "y" 

  csv_records = sync_utils.parse_csv(csv_filename)
  csv_records = [r for r in csv_records if is_valid_member_predicate(r)]
  csv_records = sync_utils.FieldJoiningWrapper.wrap_records(csv_records, "name", ["firstname", "surname"], " ")
  csv_records = sync_utils.BooleanFieldWrapper.wrap_records(csv_records, "active")

  db_records = sync_utils.ModelRecordWrapper.wrap_queryset(Player.objects.all())
  db_records = sync_utils.FieldMappingWrapper.wrap_records(db_records, 
                                                           name="get_full_name", 
                                                           email="user.email", 
                                                           mobile_phone="cell_phone",
                                                           home_phone="other_phone",
                                                           active="user.is_active")

  comparison_fields = ["email", "mobile_phone", "home_phone", "active"]
  lhsonly, rhsonly, diffs = sync_utils.report_differences(db_records, csv_records, "name", comparison_fields)

  print "\n*** Members only in db:"
  for record in lhsonly:
    print record["name"]

  print "\n*** Members only in CSV file:"
  for record in rhsonly:
    print record["name"]
    possibles = Player.objects.filter(user__last_name__iexact=record["surname"])
    if len(possibles) > 0:
      print " possibles: " + str(possibles)

    # update the DB with new members if necessary:
    if settings._WSRC_SETTINGS["sync_updates"]:
      username="_".join([record["firstname"].lower(), record["surname"].lower()])
      # skip usernames in DB already - can arise when translating unicode names to ascii usernames 
      matches = User.objects.filter(username=username) 
      if len(matches) == 0:
        persist_member_details(record)
        
  print "\n*** Record differences:"
  for name,v in diffs.iteritems():
    diff, record, csv_record = v
    player = record.target.record
    print player, diff
    if settings._WSRC_SETTINGS["sync_updates"]:
      for field,vals in diff.iteritems():
        if field == "mobile_phone":
          player.cell_phone = vals[1]
        elif field == "home_phone":
          player.other_phone = vals[1]
        elif field == "email":
          player.user.email = vals[1]
      player.save()
      player.user.save()

if __name__ == "__main__":
  if len(sys.argv) < 2:
    sys.stderr.write("USAGE: wsrc <command> [arguments]\n")
    sys.exit(1)

  os.environ.setdefault("DJANGO_SETTINGS_MODULE", "wsrc.site.settings.settings")
  logging.basicConfig(format='%(asctime)-10s [%(levelname)s] %(message)s',datefmt="%Y-%m-%d %H:%M:%S")

  import django
  if hasattr(django, "setup"):
    django.setup()

  import wsrc.external_sites.main

  command = sys.argv[1]
  args = sys.argv[2:]
  if command in ("sync", "sync-bookings"):
    wsrc.external_sites.main.cmdline_sync_bookings()

  elif command in ("sync-squashlevels"):
    wsrc.external_sites.main.cmdline_sync_squashlevels(*args)

  elif command in ("sync-leaguemaster"):
    wsrc.external_sites.main.cmdline_sync_leaguemaster(*args)

  elif command in ("sync-membership"):
    sync_membership_records(args[0])

  elif command in ("add-old-league"):
    wsrc.external_sites.main.cmdline_add_old_league(args[0])

  elif command in ("add-former-member"):
    add_former_member(args[0], args[1], args[2])

  elif command in ("add-players-for-comp"):
    import wsrc.site.competitions.models as comp_models
    for comp in comp_models.Competition.objects.all():
      if comp.id < 44:
        matches = comp.match_set.all()
        players = set()
        for m in matches:
          for i in [1,2]:
            for j in [1,2]:
              p = getattr(m, "team%d_player%d" % (i,j))
              if p is not None:
                players.add(p)
        for p in players:
          comp.players.add(p)
            

# Local Variables:
# mode: python
# End:
