# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('legacy_name', models.CharField(max_length=16)),
                ('is_knockout_comp', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='competitiongroup',
            options={'ordering': ['competition_type__name', '-end_date'], 'verbose_name': 'Competition Group'},
        ),
        migrations.AddField(
            model_name='competitiongroup',
            name='competition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.CompetitionType'),
        ),
    ]
