# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:34
from __future__ import unicode_literals

from django.db import migrations

def migrate_comp_type(apps, schema_editor):
    from wsrc.site.competitions.models import CompetitionType, CompetitionGroup
    old_groups = [ CompetitionType(id="squash_boxes", legacy_name="wsrc_boxes", name="Main Squash Boxes", is_knockout_comp=False),
                   CompetitionType(id="tournaments", legacy_name="wsrc_tournaments", name="Tournaments", is_knockout_comp=True),
                   CompetitionType(id="tournament_qualifiers", legacy_name="wsrc_qualifiers", name="Tournament Qualifier Boxes", is_knockout_comp=False) ]
    for g in old_groups:
        g.save()
    old_groups = dict([(g.legacy_name, g) for g in old_groups])
#    CompetitionGroup = apps.get_model('competitions', 'CompetitionGroup')
    for group in CompetitionGroup.objects.all():
        group.competition_type = old_groups[group.comp_type]
        group.save()
        
def unmigrate_comp_type(apps, schema_editor):
    from wsrc.site.competitions.models import CompetitionType, CompetitionGroup
    for group in CompetitionGroup.objects.all():
        group.competition_type = None
        group.save()
    CompetitionType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20180626_0933'),
    ]

    operations = [
        migrations.RunPython(migrate_comp_type, unmigrate_comp_type),
    ]
