# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:55
from __future__ import unicode_literals

from django.db import migrations

def migrate_nav_link(apps, schema_editor):
    from wsrc.site.models import NavigationLink
    for link in NavigationLink.objects.all():
        if link.is_reverse_url and link.url == "boxes":
            link.url = "boxes::squash_boxes"
            link.save()

class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20180626_1914'),
    ]

    operations = [
        migrations.RunPython(migrate_nav_link),
    ]
