# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20180627_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiontype',
            options={'verbose_name': 'Competition Type'},
        ),
        migrations.RemoveField(
            model_name='competitiontype',
            name='legacy_name',
        ),
    ]
