# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wsrc.site.usermodel.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_auto_20180406_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcardevent',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermodel.DoorEntryCard'),
        ),
        migrations.AlterField(
            model_name='doorcardlease',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.DoorEntryCard'),
        ),
        migrations.AlterField(
            model_name='doorcardlease',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.Player'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text=b'Only required for age-restricted subscriptions.', null=True, verbose_name=b'Date of Birth'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=b'email address'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='prefs_display_contact_details',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Visible'), (False, b'Not Visible')], default=None, help_text=b"Display your contact details in the club's membership list, enabling other members to contact you regarding league games etc.", verbose_name=b'Member List Visibility'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='prefs_esra_member',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Allow'), (False, b'Do Not Allow')], default=None, help_text=b'Allow the club to pass on your email address to England Squash, so they can contact you with details of how to activate your membership, which is free as part of your subscription to Woking Squash Rackets Club.', verbose_name=b'England Squash Enrolment'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='prefs_receive_email',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Allow'), (False, b'Do Not Allow')], default=None, help_text=b'Allow the club to send you general emails - news, social events, competition reminders etc.', verbose_name=b'Receive General Emails'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='season',
            field=models.ForeignKey(default=wsrc.site.usermodel.models.latest_season, on_delete=django.db.models.deletion.PROTECT, to='usermodel.Season'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.SubscriptionType'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text=b'Only required for age-restricted subscriptions.', null=True, verbose_name=b'Date of Birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prefs_display_contact_details',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Visible'), (False, b'Not Visible')], default=None, help_text=b"Display your contact details in the club's membership list, enabling other members to contact you regarding league games etc.", verbose_name=b'Member List Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prefs_esra_member',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Allow'), (False, b'Do Not Allow')], default=None, help_text=b'Allow the club to pass on your email address to England Squash, so they can contact you with details of how to activate your membership, which is free as part of your subscription to Woking Squash Rackets Club.', verbose_name=b'England Squash Enrolment'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prefs_receive_email',
            field=models.NullBooleanField(choices=[(None, b'Not Specified'), (True, b'Allow'), (False, b'Do Not Allow')], default=None, help_text=b'Allow the club to send you general emails - news, social events, competition reminders etc.', verbose_name=b'Receive General Emails'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.Player'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='season',
            field=models.ForeignKey(default=wsrc.site.usermodel.models.latest_season, on_delete=django.db.models.deletion.PROTECT, to='usermodel.Season'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.SubscriptionType'),
        ),
        migrations.AlterField(
            model_name='subscriptioncost',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='usermodel.Season'),
        ),
        migrations.AlterField(
            model_name='subscriptioncost',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermodel.SubscriptionType'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='usermodel.Subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subs_payments', to='accounts.Transaction', unique=True),
        ),
    ]
