# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0005_auto_20180514_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcardevent',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usermodel.DoorEntryCard'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subs_payments', to='accounts.Transaction'),
        ),
    ]
