#!/usr/bin/env python

import sys
import os
import os.path

from jinja2 import Environment, FileSystemLoader

if __name__ == "__main__":
  (dir, file) = os.path.split(sys.argv[1])
  env = Environment(loader=FileSystemLoader(dir))
  kwargs = dict()
  for arg in sys.argv[2:]:
    (name,val) = arg.split("=")
    try:
      val = int(val)
    except ValueError:
      pass
    kwargs[name] = val
  template = env.get_template(file)
  sys.stdout.write(template.render(**kwargs))
